/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.pigLatiniser;

import com.example.pigLatiniser.domain.Phrase;
import com.example.pigLatiniser.service.PigLatiniserService;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class PigLatiniserServiceTest {

    @Test
    void containsPigLatiniserMethod() {
        assertNotNull(PigLatiniserService.pigLatiniser("nix"));
    }

    @Test
    void shouldTranslatePhraseToPigLatin() {
        Phrase mockPhrase = new Phrase();
        mockPhrase.setOriginalPhrase("nix on the stupid");

        Phrase mockPhraseTranslation = new Phrase();
        mockPhraseTranslation.setOriginalPhrase("nix on the stupid");
        mockPhraseTranslation.setTranslatedPhrase("ixnay on the upidstay");

        Phrase mockTranslation = PigLatiniserService.translate(mockPhrase);

        assertEquals(mockPhraseTranslation.getTranslatedPhrase(), mockTranslation.getTranslatedPhrase());
    }
}
